"use client";

import { useAppContext } from "@/lib/AppContext";
import { motion } from "framer-motion";
import Link from "next/link";
import { ArrowRight, BookOpen, Target, Trophy, Clock, Rocket, LineChart, Code, AlertCircle, X } from "lucide-react";
import { useState } from "react";
import RadialProgress from "@/components/RadialProgress";
import ActivityHeatmap from "@/components/ActivityHeatmap";

export default function Dashboard() {
  const { state } = useAppContext();
  const [bannerDismissed, setBannerDismissed] = useState(false);
  
  const hasOnboarded = state.role !== null;

  const isTestDue = !bannerDismissed &&
    !!state.nextTestDueDate &&
    new Date(state.nextTestDueDate) <= new Date();

  const isFutureTest = !!state.nextTestDueDate &&
    new Date(state.nextTestDueDate) > new Date();

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      {!hasOnboarded ? (
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="max-w-5xl space-y-12 mt-8"
        >
          {/* Header Section */}
          <div className="space-y-4">
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight text-white">
              Master Your Next <span className="text-indigo-500">Interview</span>.
            </h1>
            <p className="text-zinc-400 text-lg max-w-2xl">
              An adaptive AI-powered platform that guides you from skill assessment to placement readiness with personalized roadmaps.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="glass-card p-8 rounded-2xl border border-zinc-800/50 bg-zinc-900/50 flex flex-col items-start gap-4">
              <div className="p-3 bg-zinc-800/80 rounded-lg">
                <Rocket className="w-5 h-5 text-indigo-400" />
              </div>
              <h3 className="text-xl font-semibold">Start New Journey</h3>
              <p className="text-zinc-400 text-sm mb-4">
                Define your target role, evaluate your skills, and get a custom roadmap generated by AI.
              </p>
              <Link href="/setup">
                <button className="bg-indigo-600 hover:bg-indigo-500 text-white px-6 py-2.5 rounded-lg font-medium transition-colors flex items-center gap-2 text-sm mt-auto">
                  Get Started <ArrowRight className="w-4 h-4" />
                </button>
              </Link>
            </div>

            <div className="glass-card p-8 rounded-2xl border border-zinc-800/50 bg-zinc-900/50 flex flex-col items-start gap-4">
              <div className="p-3 bg-zinc-800/80 rounded-lg">
                <LineChart className="w-5 h-5 text-emerald-400" />
              </div>
              <h3 className="text-xl font-semibold w-full">Current Progress</h3>
              <div className="w-full mt-2 space-y-2">
                <div className="flex justify-between text-sm text-zinc-400">
                  <span>Syllabus Completion</span>
                  <span>0%</span>
                </div>
                <div className="w-full bg-zinc-800/50 rounded-full h-1.5">
                  <div className="bg-emerald-500 h-1.5 rounded-full w-0"></div>
                </div>
              </div>
              <p className="text-zinc-500 text-xs italic mt-4">
                Complete your initial assessment to unlock your roadmap.
              </p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="glass-card p-6 rounded-2xl border border-zinc-800/50 bg-zinc-900/50 flex flex-col gap-3">
              <div className="p-2.5 bg-zinc-800/80 rounded-lg self-start">
                <Target className="w-4 h-4 text-indigo-400" />
              </div>
              <h4 className="font-medium">Targeted Learning</h4>
              <p className="text-xs text-zinc-400">Focus on exactly what you need for your specific role.</p>
            </div>
            <div className="glass-card p-6 rounded-2xl border border-zinc-800/50 bg-zinc-900/50 flex flex-col gap-3">
              <div className="p-2.5 bg-zinc-800/80 rounded-lg self-start">
                <Code className="w-4 h-4 text-indigo-400" />
              </div>
              <h4 className="font-medium">AI Evaluation</h4>
              <p className="text-xs text-zinc-400">Get deep insights into your strengths and weaknesses.</p>
            </div>
            <div className="glass-card p-6 rounded-2xl border border-zinc-800/50 bg-zinc-900/50 flex flex-col gap-3">
              <div className="p-2.5 bg-zinc-800/80 rounded-lg self-start">
                <LineChart className="w-4 h-4 text-indigo-400" />
              </div>
              <h4 className="font-medium">Adaptive Roadmap</h4>
              <p className="text-xs text-zinc-400">Your plan updates dynamically based on your performance.</p>
            </div>
          </div>
        </motion.div>
      ) : (
        <div className="space-y-6">
          {/* Test Due Reminder Banner */}
          {isTestDue && (
            <motion.div 
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              className="glass-card p-5 rounded-2xl border border-amber-500/30 bg-amber-500/10 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"
            >
              <div className="flex items-center gap-3">
                <div className="p-2.5 bg-amber-500/20 rounded-xl text-amber-400">
                  <AlertCircle className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="font-bold text-white text-sm">
                    Time for your {state.testFrequency === "weekly" ? "Weekly" : "Monthly"} check-in test!
                  </h3>
                  <p className="text-xs text-amber-200/80">
                    Your scheduled test was due on {new Date(state.nextTestDueDate!).toLocaleDateString()}. Take an assessment now to update your readiness score and adaptive roadmap.
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-3">
                <Link href="/assessment">
                  <button className="bg-amber-500 hover:bg-amber-400 text-black text-xs font-bold px-4 py-2 rounded-xl transition-all shadow-md">
                    Take Test Now
                  </button>
                </Link>
                <button
                  onClick={() => setBannerDismissed(true)}
                  className="text-zinc-400 hover:text-white p-1 rounded-lg hover:bg-zinc-800 transition-colors"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            </motion.div>
          )}

          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="grid grid-cols-1 md:grid-cols-3 gap-6"
          >
            {/* Readiness Score Card */}
            <div className="glass-card p-6 md:col-span-2 relative overflow-hidden group">
              <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500/10 rounded-full blur-3xl -mr-32 -mt-32 transition-transform duration-500 group-hover:scale-110" />
              <div className="relative z-10 flex h-full flex-col justify-between space-y-4">
                <div className="flex justify-between items-start">
                  <div>
                    <h3 className="text-zinc-400 font-medium mb-0.5">Current Readiness</h3>
                    <span className="text-zinc-500 text-xs font-semibold uppercase tracking-wider">Placement Setup</span>
                  </div>
                  {isFutureTest && (
                    <span className="text-[11px] font-semibold text-indigo-300 bg-indigo-500/10 px-2.5 py-1 rounded-lg border border-indigo-500/20">
                      Next check-in: {new Date(state.nextTestDueDate!).toLocaleDateString()}
                    </span>
                  )}
                </div>

                <div className="flex items-center justify-between gap-6 py-1">
                  <div className="space-y-2">
                    <div className="text-4xl sm:text-5xl font-bold tracking-tight text-white">
                      {state.readinessScore}%
                    </div>
                    <p className="text-xs text-zinc-400 max-w-[220px] leading-relaxed">
                      {state.readinessScore >= 75
                        ? "Exceptional score! You are in the high readiness tier for placement interviews."
                        : state.readinessScore >= 40
                        ? "Solid foundation. Keep completing roadmap tasks to strengthen weak areas."
                        : "Initial readiness level. Complete assessments & roadmap tasks to boost your score."}
                    </p>
                  </div>

                  <RadialProgress score={state.readinessScore} size={140} />
                </div>

                <p className="text-[11px] text-zinc-500 text-right pt-2 border-t border-zinc-800/50">
                  Keep practicing to improve your score.
                </p>
              </div>
            </div>

            {/* Profile Summary Card */}
            <div className="glass-card p-6 flex flex-col gap-4">
              <h3 className="text-zinc-400 font-medium pb-2 border-b border-zinc-800/50">Your Profile</h3>
              <div className="space-y-4 flex-1">
                <div className="flex items-center gap-3">
                  <Target className="w-5 h-5 text-indigo-400" />
                  <div>
                    <p className="text-xs text-zinc-500">Target Role</p>
                    <p className="font-medium">{state.role}</p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <Trophy className="w-5 h-5 text-indigo-400" />
                  <div>
                    <p className="text-xs text-zinc-500">Current Level</p>
                    <p className="font-medium">{state.level}</p>
                  </div>
                </div>
                <div className="flex items-center gap-3">
                  <Clock className="w-5 h-5 text-indigo-400" />
                  <div>
                    <p className="text-xs text-zinc-500">Timeline</p>
                    <p className="font-medium">{state.timelineWeeks} Weeks</p>
                  </div>
                </div>
              </div>
              <Link href="/setup" className="mt-4 text-center w-full py-2 bg-zinc-800 hover:bg-zinc-700 text-sm font-medium rounded-md transition-colors">
                View Full Syllabus
              </Link>
            </div>
            
            {/* Daily Activity Heatmap Card */}
            <ActivityHeatmap completionDates={state.taskCompletionDates} />

            {/* Quick Actions Cards */}
            <div className="md:col-span-3 mt-2">
              <h3 className="text-xl font-semibold mb-4 text-white">Quick Actions</h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                <Link href="/assessment" className="glass-card p-6 hover:border-indigo-500/50 transition-all duration-200 group relative">
                  <div className="flex items-center justify-between mb-3">
                    <BookOpen className="w-6 h-6 text-indigo-400 group-hover:scale-110 transition-transform" />
                    <ArrowRight className="w-4 h-4 text-indigo-400 opacity-0 -translate-x-1 group-hover:opacity-100 group-hover:translate-x-0 transition-all duration-200" />
                  </div>
                  <h4 className="font-medium mb-1 text-white group-hover:text-indigo-300 transition-colors">Take Mock Test</h4>
                  <p className="text-xs text-zinc-400">Evaluate skills & Generate roadmap based on your current level</p>
                </Link>
                <Link href="/roadmap" className="glass-card p-6 hover:border-indigo-500/50 transition-all duration-200 group relative">
                  <div className="flex items-center justify-between mb-3">
                    <Target className="w-6 h-6 text-indigo-400 group-hover:scale-110 transition-transform" />
                    <ArrowRight className="w-4 h-4 text-indigo-400 opacity-0 -translate-x-1 group-hover:opacity-100 group-hover:translate-x-0 transition-all duration-200" />
                  </div>
                  <h4 className="font-medium mb-1 text-white group-hover:text-indigo-300 transition-colors">View Roadmap</h4>
                  <p className="text-xs text-zinc-400">Follow your personalized 2-week daily plan</p>
                </Link>
                <Link href="/final" className="glass-card p-6 hover:border-indigo-500/50 transition-all duration-200 group relative">
                  <div className="flex items-center justify-between mb-3">
                    <Rocket className="w-6 h-6 text-indigo-400 group-hover:scale-110 transition-transform" />
                    <ArrowRight className="w-4 h-4 text-indigo-400 opacity-0 -translate-x-1 group-hover:opacity-100 group-hover:translate-x-0 transition-all duration-200" />
                  </div>
                  <h4 className="font-medium mb-1 text-white group-hover:text-indigo-300 transition-colors">Final Revision Hub</h4>
                  <p className="text-xs text-zinc-400">Rapid 7-day sprint & final placement mock test</p>
                </Link>
              </div>
            </div>
          </motion.div>
        </div>
      )}
    </div>
  );
}
